on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run k6 load test
        uses: k6io/action@v0.2.0
        env:
          SERVICE_HOSTNAME: deckchair-test.web.app
        with:
          filename: k6.js
          flags: --out csv=./load-test-results.csv

      - uses: actions/upload-artifact@v2
        with:
          name: load-test-results
          path: ./load-test-results.csv
